### ISSUE TITLE
Make Cutadapt optional

### ISSUE THREAD

**Issue by ArwaAbbas** [eclarke/sunbeam#38]
In the QC step of the pipeline, there is removal of  custom sequences (defined in the config file as Cutadapt's fwd and rev adaptors) that are introduced in the Bushman lab cDNA synthesis workup of RNA samples. These sequences would be expected to be found at both 5' and 3' ends of cDNA. In some cases, these sequences  can form long concatemers  (again a product of the Bushman lab cDNA synthesis step) and are therefore of little value to be analyzed in downstream steps.

However, these sequences would not be considered wetside artifacts in sequencing of DNA samples as they are not deliberately introduced at any point in the library preparation. 

In a typical DNA sample, it appears that these sequences are identified in 10% of reads (probably just by chance). Currently, these reads are discarded. However, in the case of DNA samples, there is no reason to discard these reads and therefore losing 10% of "real" data.

Some suggestions to address separate treatment of DNA versus cDNA samples:
1. Make cutadapt an optional additional parameter to call on reads AFTER they have been quality trimmed and paired.
2. Only trim the sequences, don't discard the reads.

This would also be important in cDNA submitted by other users who don't necessarily use the same protocol as we do.

**Comment by eclarke** [comment]
Proposed solution:

- If the adapter fields are empty, cutadapt is skipped entirely and files are symlinked into the `qc/cutadapt` directory
- Cutadapt now requires an overlap (`-O`) equal to the length of the smallest adapter sequence, which should help reduce erroneous discards. Previously this was at its default of 3, allowing a lot of reads to get discarded by mistake.

**Comment by eclarke** [comment]
Implemented in 898a9bffffed14ebef728d44c21d87b4fec16614

**Comment by ArwaAbbas** [comment]
The solution above does create symlinked files in the qc/cutadapt folder. However I've been encountering a problem in the subsequent trimmomatic step.

The specific error message is thus:

"Error in job trimmomatic while creating output files /home/arwa/17_CTOT_Longitudinal/sunbeam_test_cutadapt_output/qc/paired/CTOT_13-31-V4-S-D_R1.fastq.gz, /home/arwa/17_CTOT_Longitudinal/sunbeam_test_cutadapt_output/qc/paired/CTOT_13-31-V4-S-D_R2.fastq.gz, /home/arwa/17_CTOT_Longitudinal/sunbeam_test_cutadapt_output/qc/unpaired/CTOT_13-31-V4-S-D_R1_unpaired.fastq.gz, /home/arwa/17_CTOT_Longitudinal/sunbeam_test_cutadapt_output/qc/unpaired/CTOT_13-31-V4-S-D_R2_unpaired.fastq.gz.
RuleException:
CalledProcessError in line 59 of /home/arwa/17_CTOT_Longitudinal/sunbeam/rules/qc/qc.rules:
Command '
        trimmomatic         PE -threads 1 -phred33         /home/arwa/17_CTOT_Longitudinal/sunbeam_test_cutadapt_output/qc/cutadapt/CTOT_13-31-V4-S-D_R1.fastq /home/arwa/17_CTOT_Longitudinal/sunbeam_test_cutadapt_output/qc/cutadapt/CTOT_13-31-V4-S-D_R2.fastq         /home/arwa/17_CTOT_Longitudinal/sunbeam_test_cutadapt_output/qc/paired/CTOT_13-31-V4-S-D_R1.fastq.gz /home/arwa/17_CTOT_Longitudinal/sunbeam_test_cutadapt_output/qc/unpaired/CTOT_13-31-V4-S-D_R1_unpaired.fastq.gz         /home/arwa/17_CTOT_Longitudinal/sunbeam_test_cutadapt_output/qc/paired/CTOT_13-31-V4-S-D_R2.fastq.gz /home/arwa/17_CTOT_Longitudinal/sunbeam_test_cutadapt_output/qc/unpaired/CTOT_13-31-V4-S-D_R2_unpaired.fastq.gz         ILLUMINACLIP:/home/arwa/miniconda3/envs/sunbeam/share/trimmomatic-0.36-3/adapters/NexteraPE-PE.fa:2:30:10:8:true         LEADING:3         TRAILING:3         SLIDINGWINDOW:4:15         MINLEN:36 &> /home/arwa/17_CTOT_Longitudinal/sunbeam_test_cutadapt_output/qc/log/trimmomatic/CTOT_13-31-V4-S-D.out        ' returned non-zero exit status 1
  File "/home/arwa/17_CTOT_Longitudinal/sunbeam/rules/qc/qc.rules", line 59, in __rule_trimmomatic
  File "/home/arwa/miniconda3/envs/sunbeam/lib/python3.5/concurrent/futures/thread.py", line 55, in run

In the config file the field for cutadapt looks like this:
# Cutadapt
  fwd_adapters: []
  rev_adapters: []

Not certain why this isn't a problem in the test. 

However, including the cutadapt step with the new -o parameter generally only removes 10-100 sequence reads in each pair which is a negligible loss. But ideally want the pipeline to run even if cutadapt doesn't change the FASTQ files at all.
