### ISSUE TITLE
Workflow Error for Certain Rules 

### ISSUE THREAD

**Issue by ArwaAbbas** [eclarke/sunbeam#43]
Currently encountering the same error in calling a few rules related to contig annotation.
Specifically:

"Workflow Error:Target rules may not contain wildcards. Please specify concrete files or a rule without wildcards."

This error appears when individually calling at least the following rules. This occurs even when valid paths are given to nucleotide and protein databases in the config file. 
find_genes_mga
run_blastn
run_blastp
run_blastx

However, when calling the rule all_annotate, there is no error even though that rule includes run_blastn.

**Comment by eclarke** [comment]
Not all rules can be called on the command line. Intermediate rules require the specification of the target filenames, not the rule name. Rules beginning with "all_*" have their target filenames automatically specified based on the samples detected from the config file, and can be used on the command line*. The intermediate rules are called as part of the steps required to produce some output, and the wildcards are filled in based on the targets requested.

*If you look at the "input" sections for the "all_*" rules, you can see that the "all_*" rules use inputs produced from rules/targets.rules. If you follow the template in the targets.rules file, you can create new target lists for the particular step of the rule you're interested in.
