### ISSUE TITLE
Conda metadata issue on PMACS cluster only

### ISSUE THREAD

**Issue by varunaggarwala** [eclarke/sunbeam#45]
Conda debug or update gets stalled on the PMACS cluster.
The prompt gets hung up on 
Fetching package metadata ...

Note, this is not an issue on microb120 and 191. I am reading more about this, and it seems this issue can be due to some proxy settings on the cluster?

Do you have a quick solution for this?

**Comment by eclarke** [comment]
I can't replicate this. `conda update` works normally for me. One thing you could try is deleting that ~/miniconda3 folder and reinstalling.

**Comment by varunaggarwala** [comment]
I always delete the folder ~/miniconda3 before trying to do a fresh
install. Not sure why this error comes up repeatedly.
Thanks anyways.
