### ISSUE TITLE
mga stopped 

### ISSUE THREAD

**Issue by guanzhidao** [eclarke/sunbeam#85]
mga stopped when processing an empty "final-contigs.fa" file. This is the updated sunbeam version.
![screen shot 2017-09-22 at 1 23 55 pm](https://user-images.githubusercontent.com/22323395/30762506-37da44f2-9fb0-11e7-8875-3986121bc8bd.png)

**Comment by eclarke** [comment]
Thanks! For now I'd suggest just excluding this sample, and we'll fix this ASAP.

**Comment by eclarke** [comment]
We'll resolve this when we change ORF finders from MGA to Prodigal

**Comment by eclarke** [comment]
Fixed in #99 - Now using Prodigal and this error does not arise. Thanks for reporting!
